###
# Registro nuevo usuario
POST http://localhost:9000/api/auth/createUser HTTP/1.1
Content-Type: application/json

{
  "user": "Lorenzo",
  "email": "lorenzo@gmail.com",
  "password": "Clave5678"
}

###
# Iniciar sesion
POST http://localhost:9000/api/auth/loginUser HTTP/1.1
Content-Type: application/json

{
  "email": "lorenzo@gmail.com",
  "password": "Clave5678"
}

###
# Cerrar sesion
POST http://localhost:9000/api/auth/logoutUser HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk5OGRkNzA5MjlkMTkxMDY0MDVhMTYiLCJlbWFpbCI6ImRlbmlzZW9jYW1wby4wMEBnbWFpbC5jb20iLCJpYXQiOjE3MjEzMzk0NDYsImV4cCI6MTcyMTM0MzA0Nn0.VQxTVzYvG7b1HbRURck3GclliUnpREvq2bz2Y06rbYI

{
   "email": "lorenzo@gmail.com",
  "password": "Clave5678"
}