@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2RkOGMwZGUwYzM0YzAyYzRjNTMyNCIsImVtYWlsIjoicHJ1ZWJhMUBnbWFpbC5jb20iLCJpYXQiOjE3MTk1MjM2MzAsImV4cCI6MTcxOTUyNzIzMH0.OvdBxB6M0xj3GCBclU-0RhqkvS1XrlkpIkLL4_2eaoU
@userId = 665fb2befd81f8988a68b832
@movieId = 667d87b21cfe0888cd045c77

# ids de peliculas para probar
#667d7f594978e8cbbcb0d185
#667d7f5a4978e8cbbcb0d187
#667d87b21cfe0888cd045c77

### Obtener todos los usuarios (para obtener IDs de prueba)
GET http://localhost:9000/api/users HTTP/1.1
Authorization: Bearer {{token}}

### Obtener detalles de un usuario específico (para verificar un usuario existente)
GET http://localhost:9000/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### Añadir una película a la lista de favoritos de un usuario
PUT http://localhost:9000/api/user/liked/{{userId}}/{{movieId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener detalles de un usuario específico (para verificar que se sumo la pelicula)
GET http://localhost:9000/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### Borra la pelicula
DELETE http://localhost:9000/api/user/liked/{{userId}}/{{movieId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener detalles de un usuario específico en cuanto a sus peliculas favoritas (para verificar que se borro la pelicula)
GET http://localhost:9000/api/user/liked/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
