@token =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTg2ZjMwOTk3MDJkNmNlYTU2ZGQ2NiIsImVtYWlsIjoiUm9iZXJ0YUZsb3Jlc0BnbWFpbC5jb20iLCJpYXQiOjE3MjEyNzYwNzAsImV4cCI6MTcyMTI3OTY3MH0.40aSlothp8vdrqIYac_yZfsdioFY_exXttVFC-0A2pM
@userId= "66986f3099702d6cea56dd66"




### Obtener detalles de un usuario específico (para verificar un usuario existente)
GET http://localhost:9000/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### Añadir una película a la lista de favoritos de un usuario
PUT http://localhost:9000/api/user/liked/{{userId}}/{{movieId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener detalles de un usuario específico (para verificar que se sumo la pelicula)
GET http://localhost:9000/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### Borra la pelicula
DELETE http://localhost:9000/api/user/liked/{{userId}}/{{movieId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener detalles de un usuario específico en cuanto a sus peliculas favoritas (para verificar que se borro la pelicula)
GET http://localhost:9000/api/user/liked/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
