@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2RkOGMwZGUwYzM0YzAyYzRjNTMyNCIsImVtYWlsIjoicHJ1ZWJhMUBnbWFpbC5jb20iLCJpYXQiOjE3MTk1MzExNDMsImV4cCI6MTcxOTUzNDc0M30.kyQZrlMTMcUvgKEQvCDxuGWxrhRA1Ep3fVyuiMd38RQ
@userId = 6697d27fa2fdd90dfbeb55b8


### Crear película
POST http://localhost:9000/api/movies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTc0MTFhNmQwOTVhNGZhOGQwNjAwMiIsImVtYWlsIjoidHJlbnphQGdtYWlsLmNvbSIsImlhdCI6MTcyMTIyNTgyNiwiZXhwIjoxNzIxMjI5NDI2fQ.8cAkuDWRoPvrepxAecPHCEVHsnQ2W6D_rDLlbx1QeKw

{
  "title": "Harry Potter",
  "director": "JK Rolling",
  "year": 2003,
  "genre": "Fantasy",
  "rating": 10,
  "media_type": "movie",
  "trailerUrl": "https://www.youtube.com/watch?v=YoHD9XEInc0",
  "overview": "A magic world"
}

### Crear serie
POST http://localhost:9000/api/movies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTc0MTFhNmQwOTVhNGZhOGQwNjAwMiIsImVtYWlsIjoidHJlbnphQGdtYWlsLmNvbSIsImlhdCI6MTcyMTIyNTgyNiwiZXhwIjoxNzIxMjI5NDI2fQ.8cAkuDWRoPvrepxAecPHCEVHsnQ2W6D_rDLlbx1QeKw


{
  "name": "Breaking Bad",
  "director": "Vince Gilligan",
  "year": 2008,
  "genre": "Drama",
  "rating": 9.5,
  "media_type": "tv",
  "trailerUrl": "https://www.youtube.com/watch?v=HhesaQXLuRY",
  "overview": "A high school chemistry teacher turned methamphetamine producer navigates the dangers of the drug trade with his former student."
}

### Obtener todas las películas y series
GET http://localhost:9000/api/movies HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTc0MTFhNmQwOTVhNGZhOGQwNjAwMiIsImVtYWlsIjoidHJlbnphQGdtYWlsLmNvbSIsImlhdCI6MTcyMTIyNTgyNiwiZXhwIjoxNzIxMjI5NDI2fQ.8cAkuDWRoPvrepxAecPHCEVHsnQ2W6D_rDLlbx1QeKw



### Buscar película por ID
GET http://localhost:9000/api/movies/{{userId}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTc0MTFhNmQwOTVhNGZhOGQwNjAwMiIsImVtYWlsIjoidHJlbnphQGdtYWlsLmNvbSIsImlhdCI6MTcyMTIyNTgyNiwiZXhwIjoxNzIxMjI5NDI2fQ.8cAkuDWRoPvrepxAecPHCEVHsnQ2W6D_rDLlbx1QeKw


### Eliminar película por ID
DELETE http://localhost:9000/api/movies/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}